src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface,PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private string $email;

    #[ORM\Column(type: 'json')]
    private array $roles = ['ROLE_USER'];

    #[ORM\Column(type: 'string')]
    private string $password;

    private string $plainPassword;


    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Task::class)]
    private Collection $tasks;

    public function __construct()
    {
        $this->id = null;
        $this->tasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }

   
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }
    public function getPlainPassword(): string
    {
        return $this->plainPassword;
    }
    
    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    
    public function getSalt(): ?string
    {
       
        return null;
    }

    public function eraseCredentials(): void
    {

     

    }
    
}

templates/_partial/_navbar.html.twig
{% block navbar %}
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<a class="navbar-brand" href="{{ path('app_home') }}">Task Test</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{{ path('app_home') }}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ path('app_calandar') }}">Calendar</a>
					</li>
					{% if app.user %}
						<li class="nav-item">
							<span class="nav-link">connecté en tant que :
								{{ app.user.username }}</span>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{{ path('app_register') }}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ path('app_login') }}">Login</a>
						</li>
					{% endif %}
					<li class="nav-item">
						<a class="nav-link" href="{{ path('task_new') }}">Add Task</a>
					</li>
					<li class="nav-item">
						<a id="logout-link" class="nav-link" href="{{ path('app_logout') }}">Déconnexion</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
{% endblock %}